# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Nsy4aGwy3rm5f5tmwe1bohqRUlD+cOhJdnxH6cduwMNGeE8v6/MQ9vT4OnS4fyz2qoy5RST5qIxBMqrF9479SwSCeRLu6ivRa47f/Ssu9S4Y5xi/srXoaSE+XWqTMhOx9sFWArteCpBXAw2+nLk4rnE3FA0dJy/IhdEU0j9ZUhpOOjnnCxSoDRCXRYeZfbngVUyN0qnNpUrxXQTB+ftztitNQWq5kWD+ndaZRtC+L0c4i4QtL17nQwP1DnANaAgvRL9e63Lc3KnIauYr5hifZJv0SfKnQ29raCQl8K91ihm1kSupwZ9Y7C3csJD0Glb7JAcMx2kkwAp7fjnzFxAfAzmPHUFgGndwcCeijNEHzVFo9qEZqyZSTuFFQNfoqS52/proDoWuSMmMxCcllviLbMnE71X96hF/15LMS2CxeurSXMKK0BXz3lavNMbD+mv5xKOj5PCn88+eql1q/7ENyyWu2snVC9krCZyjE0rM+FI+WNTry6vRH93WcYoWIXv7jVs/A3zFXS0K6B4i/8FV9jeu8m7M4ZCXorKr+EuosiJq0IJ9CRAc/mnNHanX74fvL2BMCmxRpjSAKPh761K3QITtP+RCjF1D0FzNDIE/4TutUlSUqzJ1HKmbSfnHju4T3dVUu1zt0N5fGMH1wFf5E5cs6SdDaL4NadbfdovcvtU="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
