travis:
  secure:
    BINSTAR_TOKEN: Nsy4aGwy3rm5f5tmwe1bohqRUlD+cOhJdnxH6cduwMNGeE8v6/MQ9vT4OnS4fyz2qoy5RST5qIxBMqrF9479SwSCeRLu6ivRa47f/Ssu9S4Y5xi/srXoaSE+XWqTMhOx9sFWArteCpBXAw2+nLk4rnE3FA0dJy/IhdEU0j9ZUhpOOjnnCxSoDRCXRYeZfbngVUyN0qnNpUrxXQTB+ftztitNQWq5kWD+ndaZRtC+L0c4i4QtL17nQwP1DnANaAgvRL9e63Lc3KnIauYr5hifZJv0SfKnQ29raCQl8K91ihm1kSupwZ9Y7C3csJD0Glb7JAcMx2kkwAp7fjnzFxAfAzmPHUFgGndwcCeijNEHzVFo9qEZqyZSTuFFQNfoqS52/proDoWuSMmMxCcllviLbMnE71X96hF/15LMS2CxeurSXMKK0BXz3lavNMbD+mv5xKOj5PCn88+eql1q/7ENyyWu2snVC9krCZyjE0rM+FI+WNTry6vRH93WcYoWIXv7jVs/A3zFXS0K6B4i/8FV9jeu8m7M4ZCXorKr+EuosiJq0IJ9CRAc/mnNHanX74fvL2BMCmxRpjSAKPh761K3QITtP+RCjF1D0FzNDIE/4TutUlSUqzJ1HKmbSfnHju4T3dVUu1zt0N5fGMH1wFf5E5cs6SdDaL4NadbfdovcvtU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
