travis:
  secure:
    BINSTAR_TOKEN: DbXI7SEoIGahhxb5sC8uwxebQ+9R66W8g7fOmgtoTCZxqSuYHZsBD4NpXvY/BvY0GPODfdniKP1R8tMRjq7dj3K90j7vH5R4/EsMFbK51SgeBqF0+AgBng8dOZaTne0UgEWaRrFYzQ41QTODMisGjHmisd4L49OqNjU6+2iMxyHmoI/m7Dlonw/LKG6wnhwQOumLo86C22nafpSdJ66D8Jf5PmQfWIgcuYE61o1OHqo92cXfebD31jmShAAknQauESp+ht5xFIV7t+HiIUHLxSog8H/pyJ2jUT96/Cxg9trhDm5Fp+JaEBOe++RKySgSr3dC7xUaucYu70b5uXFSyqMytE105p661gnxB/B9xEOqin6cpoMnGMjVQeIHSeBBbFLIiamcu0WaC9QCKBruaIceurLZHWS2L66OaN6pbL1mse59IPHm/DM+i93NK950P6O4n9sC2/bTUEmV6Fsk20hSU851e80ro+fzZBOCZgXjHrUcPe8CgcqQUltXEIeHFj71C1QRu8EpA2eG+x1QUkBAaXOEuxzZAIgkYlmhXdB8oyZRqgA1bzPydLmXZOkXDQ0kGlMs4Ads5SoMUPk+YmgQpFE27pSOSIPdNtq2lDCyCqaDabJDeERIXsfGqv+6ToGtwwm6B8VgV2FTPhqfi/lJaFpjJ0kTG7uWrIbgec8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
