travis:
  secure:
    BINSTAR_TOKEN: SwOiT5aZLYBZQawu7CL2zBr3mhpDpYEeEhdf5J3q6lYh7F/riujo/jNYIDr8fDtNcWvPrDNiX+rjhkPWYn05QRKj+N3KexKCs2DamF2IAzHq940qHRqHCYjaeA9EKdyZUmOTfrueKgDGUvhS6WdngtoEbMEzO8biI8Z3BT7qblwckJbNvEqeIjCfebkgWENomaMBrdhN9n6yHJFOgIt25SjfCuk9XIm8HkeS+elqWRF+/V7kZGHZiPz727hKzc51U4hnq2PdwKskJalz9uts5UL73FwEzM3sE/8zjw9DQAYjGlvIKo+eWjdCtf0zaOE8nn/usLM0AyCRD0Y2KexXyFi4MwzVsQRwO9Q0l+gdOR5C0RBiVqpm+ZCFas5P2s0SseBzN4f73zvon6xt70bwtv8+SLamrp376bRpc1ExD/jk/K+PJyHNFDSp+YHuX9TDs4dDYsIK76NJSKVIrjiNxZ6NKq/5ohiYr91QIQ9ED/V7l9QQgGkHIjfGfdbxPhPvEUmBJp7m8TC0hnWjqz5pJLkjiouDtWLGHLNJqTTlngSjwbkvejimaSqKtN9nP4FTth8EoMPDb3zjLOmBps3Pv7sbymViRVJnrW7don4dw5PFIs4gOfFZwf0tQRIhbPd7bT6hVbWpIZDlhW2Xe2XT1U56L3WSxt+Et4Q8uZgaQ8k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
